install:
	@mkdir -p /home/me/inc/
	@cp ArrayList.h LinkedList.h Queue.h Stack.h RandomSupport.h TimeSupport.h /home/me/inc/
	@echo
	@echo "Installed headers"
	@echo "    ArrayList.h"
	@echo "    LinkedList.h"
	@echo "    Queue.h"
	@echo "    Stack.h"
	@echo "    RandomSupport.h"
	@echo "    TimeSupport.h"
	@echo
	@echo "You can now use #include<filename> for the above files in your C++ programs"
	@echo "without having a copy of the file in your working directory"
	@echo